import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '<pages>/styles/Home.module.css'
import Header from '../components/mainPage/Header'
import Banner from '../components/mainPage/Banner'
import SmallCard from '../components/mainPage/smallCard'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  try {
    const response = await fetch('https://www.jsonkeeper.com/b/4G1G');
    const exploreData = await response.json();
    return {
      props: {
        exploreData
      }
    };
  } catch (error) {
    console.log(`An error occurred: ${error}`)
    return { props: {} };
  }
}

type Props ={ 
  exploreData?: ExploreSectionData[],
}

export default function Home({ exploreData }: Props) {
  
  return (
    <div className="bg-white">
      <Head>
        <title>Airbnb Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Section */}
      <Header />
      {/* Banner Section */}
      <Banner />
      {/* Explore Nearby Section */}
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5 ml-10 sm:ml-0'>Explore Nearby</h2>
          {/* static rendeing  */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {exploreData?.map((place, index) => (
            <SmallCard key={`${place.location}-${index}`} place={place}  />
          ))}
          </div>





        </section>       
      </main>
      
      
     </div>  
  )
}



 