import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '<pages>/styles/Home.module.css'
import Header from '<pages>/components/mainPage/Header'
import Banner from '<pages>/components/mainPage/Banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="bg-white">
      <Head>
        <title>Airbnb Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Section */}
      <Header />
      {/* Banner Section */}
      <Banner />
      {/* Explore Nearby Section */}
      
     </div>  
  )
}
